### ISSUE TITLE
Opera support

### ISSUE THREAD

**Issue by Ripley63** [PedalPlayground/pedalplayground#1014]
Just a heads-up about a strange behaviour in Opera (latest version), in Win10.

Clicking on "Add pedalboard" or "Add pedal" doesn't do anything.
Boards and pedals are added directly by selecting them from the dropdown lists.

BUT

the first item in both lists is preselected (has a different color than the rest) and it's impossible to add it, unless you first select some other items, and only then you can re-select the first one...

**Comment by XlosVSM** [comment]
Hi, it's been about 1.5 years since you posted this issue and I am wondering is it still a problem. If not, could you close the issue. If it is, please say what is still wrong.

**Comment by Ripley63** [comment]
Hi, this issue seems fixed by now.
