### ISSUE TITLE
Improvement/fix: Dimensions of "Donner AB/Y" too small

### ISSUE THREAD

**Issue by trukul** [PedalPlayground/pedalplayground#1446]
The "Donner AB/Y" has pretty much the same dimensions as the "Mooer Micro ABY MKII".

Dimensions "Donner AB/Y": **42x93.5x52mm** (https://donnerde.com/products/donner-aby-box-gitarre-effektpedal-aby-kanalschalter-mini-gitarre-pedal-true-byapss)

As you can see in the attached screenshot, the "Donner AB/Y" appears way smaller though (the dimensions of the "Mooer Micro ABY MKII" fit to the rest of the pedals on my virtual board)

![Bildschirm­foto 2023-03-08 um 00 05 52](https://user-images.githubusercontent.com/32384545/223574418-45b04e4b-33ed-4d85-ae3e-f183e97ac794.png)

**Comment by ArislanShiva** [comment]
Seems like @XlosVSM may have fixed this in his most recent PR.
