### ISSUE TITLE
Kingsley Page TS

### ISSUE THREAD

**Issue by edgestrat** [PedalPlayground/pedalplayground#1453]
Width: 3.875 inches
Height: 4.75 inches

![kingsleypagets675](https://user-images.githubusercontent.com/127613278/224493143-6fb8ebc0-6c62-4a78-b20b-3fd5548f0d23.png)

**Comment by theCOkid** [comment]
This would be great to add! Thanks!

**Comment by edgestrat** [comment]
Thanks!
