### ISSUE TITLE
Microcopy | Canvas Scale definition in app may be confusing

### ISSUE THREAD

**Issue by iiimonfiiire** [PedalPlayground/pedalplayground#1506]
Current explanation on Canvas Scale dialog that appears when clicking on exclamation mark (!) icon is:
"The canvas scale is the number of pixels on the canvas that equal 1 inch. Increasing the value will increase the size of everything on the canvas equally, but your layout will need some correcting."

The main issue is in "the number of pixels on the canvas that equal 1 inch".
Was the intention "1 inch" or "1 inch^2"? 
Here is suggested microcopy for either case:
1. "the number of pixels that fit in a 1-inch line on your display screen"
2. "the number of pixels that fit an area of 1 square inch (in^2) on your display screen; resolution; pixel density."

**Comment by ArislanShiva** [comment]
Would something like this make more sense?

![scale](https://user-images.githubusercontent.com/14098250/235951731-380509ec-1290-43fa-9bbe-c947fb81ff37.jpg)
![modal](https://user-images.githubusercontent.com/14098250/235951754-45b3f5db-08c8-4a7e-9851-4de75f1803f0.jpg)

@tehtrav please weigh in.

**Comment by iiimonfiiire** [comment]
@ArislanShiva i would suggest the following:  
Label: Resolution
Unit: PPI
Tooltip: Enter your <a href="url-to-how-to-calculate-screen-resolution">screen resolution</>. Changing this will change the size of ...

I would also suggest that the tooltip icon be changed to an "i" (for "info") or a question mark ("?").
