### ISSUE TITLE
Multiple FTelettronica pedals have empty background images

### ISSUE THREAD

**Issue by JHunnicutt** [PedalPlayground/pedalplayground#1660]
Many pedals from the FTelettronica category do not show up when selected. Nothing appears when a user selects the pedal, however, an empty div can still be selected and interacted with.

The pedals in question:

- Anonymous Flange
- Atrocity Distortion
- Black Hole Analog Octaver
- Catastrophizer Distortion
- Cotton Candy Digital Reverb
- Das Model
- Dystopian Fuzz
- Echo Maniac Kid

Tested in both Firefox and Chrome

**Comment by ArislanShiva** [comment]
I'll take a look at these.  The images don't even reside in the folders, maybe @XlosVSM deleted them by accident.

**Comment by XlosVSM** [comment]
I probably did accidentally delete them at some point, I'll find and restore them

**Comment by JHunnicutt** [comment]
Yeah, when I was trying to troubleshoot with the devtools, it appeared that the image file wasn't even showing up in the dom.
