### ISSUE TITLE
Pedal Request: Various pedalboard risers

### ISSUE THREAD

**Issue by Benjamin-RM** [PedalPlayground/pedalplayground#1696]
Various pedalboard risers:

### **Goodwood Audio** 

- 12" LIFT - 12" x 5"  

![image](https://github.com/PedalPlayground/PedalPlayground.github.io/assets/90400280/bf52d3c9-5cda-4d68-8e9e-0d430238383f)

- 16" LIFT - 16" x 5"  

![image](https://github.com/PedalPlayground/PedalPlayground.github.io/assets/90400280/45d1e5ab-ac23-46f7-81eb-7003908d18ce)

- 21" LIFT - 21" x 5"

![image](https://github.com/PedalPlayground/PedalPlayground.github.io/assets/90400280/558eaee3-b095-456b-ad6f-219d7e2d79e3)

### **Mono** 

Pedalboard Rise - W 3.54" x H 5.12" 

![image](https://github.com/PedalPlayground/PedalPlayground.github.io/assets/90400280/28841eb2-1c1d-4291-b691-523ff6498f8b)

Pedalboard Rise+ -  W 7.09" x H 5.12"

![image](https://github.com/PedalPlayground/PedalPlayground.github.io/assets/90400280/8bd6d9f8-0bcf-430e-bb3e-85ea9542bfe8)

**Comment by Benjamin-RM** [comment]
Page links:

Goodwood Audio https://goodwoodaudio.com/products/lift?variant=39802138624191

Mono Creators

**Comment by tehtrav** [comment]
Those GW risers are neat. Will definitely add them soon. The Mono ones are tricky. Do you know if the measurements are the overall footprint or just the flat pedal area?

**Comment by Benjamin-RM** [comment]
Good question. I had assumed the dims were for the total footprint but I can't confirm it. I can't find any flat photos either. 

Perhaps it makes sense to just focus on the GW ones them, I'll edit the post.
