### ISSUE TITLE
Commit that removed CNAME broke www.pedalplayground.com

### ISSUE THREAD

**Issue by nklmilojevic** [PedalPlayground/pedalplayground#1703]
Hi,

This commit by @tehtrav seemingly broke www.pedalplayground.com:

https://github.com/PedalPlayground/pedalplayground/commit/cf9081b32e835025269cab5ef3f530e78cc6eb20

**Comment by Benjamin-RM** [comment]
Came here to flag the same issue. Is it possible to repair it?

**Comment by nklmilojevic** [comment]
As far as I can see the A record now resolves to digitalocean - probably the team behind PedalPlayground is moving it to a separate digitalocean instance rather than GH Pages.

**Comment by nklmilojevic** [comment]
Ok, seems online again, thanks!

**Comment by tehtrav** [comment]
No problem! Thanks for keeping an eye out

**Comment by Benjamin-RM** [comment]
I'm still getting a 404 on the page at pedalplayground.com ?

<img width="704" alt="image" src="https://github.com/PedalPlayground/pedalplayground/assets/90400280/d34187c4-3c40-4124-b70f-cd141cf5d39c">
