### ISSUE TITLE
Fender Waylon Phaser pedal issue

### ISSUE THREAD

**Issue by dirtyfrets** [PedalPlayground/pedalplayground#1705]
Hi and thanks for adding the Fender Waylon Jennings Phaser pedal. When I add it, it appears as a transparent black pedal instead of what it actually looks like.

Also thanks for adding the EHX pico series, but the Pico Platform compressor was not included in the adds.

**Comment by ArislanShiva** [comment]
Sorry, was just a file name issue.  Will be fixed soon.

**Comment by XlosVSM** [comment]
The EHX Pico Platform will be added with #1610 as soon as @tehtrav merges it
