### ISSUE TITLE
Fix dimensions:  Vongon Polyphrase

### ISSUE THREAD

**Issue by Benjamin-RM** [PedalPlayground/pedalplayground#1711]
Dimensions for the **Polyphrase** should be updated to match those of the **Ultrasheer**  

Correct dimensions are:

- 6.5" wide

- 5.5" long

See below for the current mismatch 😊

<img width="461" alt="image" src="https://github.com/PedalPlayground/pedalplayground/assets/90400280/358320d1-ab51-4c92-9559-7082d8b2ff37">

**Comment by ArislanShiva** [comment]
Whoa, how did that happen lol.
