### ISSUE TITLE
Pedal Request: Canvas Tuner Walrus Audio

### ISSUE THREAD

**Issue by gp-andres** [PedalPlayground/pedalplayground#1712]
Height:
2.21"
Width:
2.42"
Depth:
4.55"
![310308B4-2627-4179-8796-1B329FB34FB5](https://github.com/PedalPlayground/pedalplayground/assets/148746784/1b3c1ae7-0257-493d-82df-fbbfa4e284e1)

**Comment by ArislanShiva** [comment]
It's already been added.
