### ISSUE TITLE
Request: GROBERT EFFECTS THE ONE CHORUS

### ISSUE THREAD

**Issue by oscarthebear** [PedalPlayground/pedalplayground#1730]
here is the link: https://www.littleboxeffects.com/product/grobert-effects-the-one-chorus
dimensions are: 7.35 x 4.65
<img width="481" alt="Screenshot 2023-11-13 at 11 57 32 PM" src="https://github.com/PedalPlayground/pedalplayground/assets/58862223/8d7c5951-73cc-4def-aaa4-4b8801c389fd">

**Comment by oscarthebear** [comment]
@ArislanShiva thanks for your hardwork man! is there any way we can support you as well as @tehtrav

**Comment by ArislanShiva** [comment]
> @ArislanShiva thanks for your hardwork! is there any way we can support you as well as @tehtrav

That's much appreciated but totally not necessary.  Just support @tehtrav with the new server costs! 😉
