### ISSUE TITLE
[bug] search no longer works in chrome and dropdowns immediately close in firefox

### ISSUE THREAD

**Issue by ddejohn** [PedalPlayground/pedalplayground#1755]
app is unusable in both browsers for different reasons :(

also noticing significant delay in opening the dropdown menus in chrome

**Comment by XlosVSM** [comment]
Just making sure, have you tested on other devices or networks?

**Comment by mstef** [comment]
I checked in these browsers and everything is fine:
Chrome 119.0.6045.199
Firefox 120.0.1

**Comment by ArislanShiva** [comment]
> app is unusable in both browsers for different reasons :(
> 
> also noticing significant delay in opening the dropdown menus in chrome

Are you still having issues?

**Comment by ddejohn** [comment]
> Just making sure, have you tested on other devices or networks?

I did not check other devices or networks, no.

> Are you still having issues?

I am no longer having issues -- not sure what was up, the UI was briefly different. I should've added some screen captures.
