### ISSUE TITLE
Pedalboard Request: Pivotal Pedalboards P-Series

### ISSUE THREAD

**Issue by PivotalPedalboards** [PedalPlayground/pedalplayground#1766]
@ArislanShiva These aren't PNGs but I'm guessing you'd prefer to create your own graphics like you did with the X-Series last time? Everything should be close to scale but if a labeled dimension conflicts with the given image, trust the dimension (position of deck cutaways). Let me know if you need any further details. Thanks so much!

![P14 Full Deck](https://github.com/PedalPlayground/pedalplayground/assets/119954542/011aff86-e26f-4d8c-8e08-7314bdc307be)
![P20 Full Deck](https://github.com/PedalPlayground/pedalplayground/assets/119954542/6184d9b2-1316-40b3-8815-7a08668493b0)
![P20 Upper (Single Cutaway)](https://github.com/PedalPlayground/pedalplayground/assets/119954542/fcd4b3cc-0092-48f7-bb3a-1e565fdf8fbe)
![P26 Full Deck](https://github.com/PedalPlayground/pedalplayground/assets/119954542/aeed439c-f8ae-4800-8b47-35007b1935f8)
![P26 Upper (Double Cutaway)](https://github.com/PedalPlayground/pedalplayground/assets/119954542/033fb87c-0934-4c87-a347-7bb5a6f31e86)
![P26 Upper (Single Cutaway)](https://github.com/PedalPlayground/pedalplayground/assets/119954542/8819ac50-f6c8-4137-a65e-9da1bf078966)
![P31 Full Deck](https://github.com/PedalPlayground/pedalplayground/assets/119954542/02a7bdc2-482c-44b2-ad69-88599ec47bb3)
![P31 Upper (Single Cutaway)](https://github.com/PedalPlayground/pedalplayground/assets/119954542/2466b6ba-decb-4a80-baba-2e4516e75d56)
![P31 Upper (Double Cutaway)](https://github.com/PedalPlayground/pedalplayground/assets/119954542/7a3fc02b-4361-403e-a293-1309081bf6e4)

edit: added the P31 sizes

**Comment by ArislanShiva** [comment]
@PivotalPedalboards Sorry I've been putting this off...

Here's my Illustrator file with the X-Series boards if you wanna take a crack at it:

https://drive.google.com/file/d/1_nA5rj-vjzWo2Fp_OQHLv_Dydvl3DIcC/view?usp=sharing

**Comment by PivotalPedalboards** [comment]
Thanks so much, this is extremely helpful! If it's no trouble, could I possibly get the deck cutaway files as well? This has made things so much easier, and, very well done graphics on your part by the way.
Thanks again

**Comment by ArislanShiva** [comment]
Everything should be contained within the file.  Each model is on a separate artboard and you can separate the individual components in the layers panels (assuming you're opening the file in AI and not PS).

**Comment by PivotalPedalboards** [comment]
P14 Lower
15.25" x 13.6.25"
![P14 Lower](https://github.com/PedalPlayground/pedalplayground/assets/119954542/ffe8a265-7f84-415b-ac41-2f74a35893e4)

______________________
P14 Full Deck
13.75" x 6"
![P14 Full Deck](https://github.com/PedalPlayground/pedalplayground/assets/119954542/7fba8b19-0a9a-4300-9827-9e2af2b6ebf6)

______________________
P20 Lower
21.75" x 13.625"
![P20 Lower](https://github.com/PedalPlayground/pedalplayground/assets/119954542/c89901c5-650b-44f0-9502-bf3a3b101a12)

______________________
P20 Full Deck
20.25" x 6"
![P20 Full Deck](https://github.com/PedalPlayground/pedalplayground/assets/119954542/5e6e9808-3c60-4412-a47e-a1aa8858a729)

______________________
P20 Single Cutaway
20.25" x 6"
![P20 Single Cutaway](https://github.com/PedalPlayground/pedalplayground/assets/119954542/9aec9f13-b3b8-4b90-b3a3-88cffbcc80e2)

______________________
P26 Lower
27.75" x 15.625"
![P26 Lower](https://github.com/PedalPlayground/pedalplayground/assets/119954542/06170d1f-9b9e-4ada-98aa-3e86872f03b4)

______________________
P26 Full Deck
26.25" x 8"
![P26 Full Deck](https://github.com/PedalPlayground/pedalplayground/assets/119954542/cdfbdc7d-207e-42c8-b915-405561c1435b)

______________________
P26 Single Cutaway
26.25" x 8"
![P26 Single Cutaway](https://github.com/PedalPlayground/pedalplayground/assets/119954542/199c4dba-3f02-4b9b-9f50-d3060d1014b3)

______________________
P26 Double Cutaway
26.25" x 8"
![P26 Double Cutaway](https://github.com/PedalPlayground/pedalplayground/assets/119954542/cc3b574c-f6bd-4951-8f8f-a50727f9e692)

______________________
P31 Lower
32.25" x 15.625"
![P31 Lower](https://github.com/PedalPlayground/pedalplayground/assets/119954542/9f00fb79-341d-45b2-a5b1-ab708cea31bf)

______________________
P31 Full Deck
30.75" x 8"
![P31 Full Deck](https://github.com/PedalPlayground/pedalplayground/assets/119954542/0c404f14-48e8-43df-bdbd-72b8f21055c7)

______________________
P31 Single Cutaway
30.75" x 8"
![P31 Single Cutaway](https://github.com/PedalPlayground/pedalplayground/assets/119954542/b89ff670-0077-415b-8a54-219fa3353dc3)

______________________
P31 Double Cutaway
30.75" x 8"
![P31 Double Cutaway](https://github.com/PedalPlayground/pedalplayground/assets/119954542/df2d8c4c-8a1c-4be4-ae50-8083502f89c6)
