### ISSUE TITLE
Keeley Muse Driver Overdrive

### ISSUE THREAD

**Issue by gp-andres** [PedalPlayground/pedalplayground#1800]
![IMG_1964](https://github.com/PedalPlayground/pedalplayground/assets/148746784/3efba9bf-5229-452f-b4e8-9a84fa3bf924)

Dimensions (L x W x H): 127 x 67 x 70 mm

**Comment by ArislanShiva** [comment]
> Before you submit, please consider the following:
> - New releases from all major builders are added to the database automatically -- there is no need to make a request for those,
> - Please check to see if your pedal request hasn't already been covered by a [pending pull](https://github.com/PedalPlayground/PedalPlayground.github.io/pulls) by one of our contributors,
