### ISSUE TITLE
Pedal Request: XTS Precision Overdrive

### ISSUE THREAD

**Issue by rockrockrokk** [PedalPlayground/pedalplayground#1813]
XTS Precision Overdrive
(2.85in x 4.5in)
![XTS Precision Overdrive](https://github.com/PedalPlayground/pedalplayground/assets/160074168/a434064d-29cb-4281-9f84-36984c7efa3a)

**Comment by ArislanShiva** [comment]
This one is already in the database listed as "XTS Precision Multi-Drive"

Please close this issue, thanks.
