### ISSUE TITLE
Pedal request: PolarBear Petrichor

### ISSUE THREAD

**Issue by dbow** [PedalPlayground/pedalplayground#1819]
Size (L x W x H)
4.6 x 3.62 x 2.24 in

![petrichor](https://images.squarespace-cdn.com/content/v1/6541667ab94d135a1ae5e4f5/1702429302180-MZS6CR49NWE4655EQOIV/ptr.jpg?format=1500w)

**Comment by ArislanShiva** [comment]
Unfortunately this image is unusable due to the angle it was taken.  Do you have a direct top-down picture of the pedal?

**Comment by dbow** [comment]
I think the best I could do at the moment is this:
![petrichor](https://rvb-img.reverb.com/image/upload/s--5N7ig7go--/a_0/f_auto,t_large/v1709145345/e7nm20tsy5jejuyffzef.jpg)

If that doesn't work I should be able to get a better one in the next week or two.
