### ISSUE TITLE
Pedal requests: Mooer Micro Preamp series (1-10)

### ISSUE THREAD

**Issue by GreenSky91** [PedalPlayground/pedalplayground#1820]
There’s 20 of them, even though I’m only interested in one or two I think it’s a no brainer to include them all as they all model specific real amplifiers. 😅 they’re all 3.68” x 1.65”. 

001 - Gas Station
![IMG_8090](https://github.com/PedalPlayground/pedalplayground/assets/132704999/5eb0ec84-9331-4a82-ab62-5b0af856e579)

002 - UK Gold
![IMG_8091](https://github.com/PedalPlayground/pedalplayground/assets/132704999/9c648ba1-58bb-4e8d-9712-678eebd4b14d)

003 - Power-Zone
![IMG_8092](https://github.com/PedalPlayground/pedalplayground/assets/132704999/55540a1c-0eae-4fac-a520-c66ac2c27562)

004 - Day Tripper
![IMG_8093](https://github.com/PedalPlayground/pedalplayground/assets/132704999/428902a7-0545-4fc8-b1e1-4eaeee948fca)

005 - Brown Sound
![IMG_8094](https://github.com/PedalPlayground/pedalplayground/assets/132704999/513af478-9afb-41d8-8ac1-d1c1dc027930)

006 - US Classic deluxe
![IMG_8095](https://github.com/PedalPlayground/pedalplayground/assets/132704999/8eb9178f-1162-4e87-aaaf-f6d33e1d5df5)

007 - Regal Tone
![IMG_8096](https://github.com/PedalPlayground/pedalplayground/assets/132704999/4a6b57ac-4d65-4770-8c27-33b8f0f7ee36)

008 - Cali-MK 3
![IMG_8097](https://github.com/PedalPlayground/pedalplayground/assets/132704999/970c4c5b-a54c-4090-b46a-fd60633ba76a)

009 - Black Night
![IMG_8098](https://github.com/PedalPlayground/pedalplayground/assets/132704999/51d9cf5b-9b76-473d-97fb-de6da01c5df5)

010 - Two Stone
![IMG_8099](https://github.com/PedalPlayground/pedalplayground/assets/132704999/0bedc402-01a1-48a3-b342-b5d1690eb415)

**Comment by ArislanShiva** [comment]
Tell me the ones you're specifically interested in and I can add those.

**Comment by GreenSky91** [comment]
Mostly 005 and 012, but also digging the purple on the 009 😅

**Comment by GreenSky91** [comment]
Hi, bringing this old thread back… I’ve been curious about the Micro Preamps 006 and 017. Any chance those can be added yet?

![Image](https://github.com/user-attachments/assets/5013569c-b3da-453d-bdde-07278b5991ee)
