### ISSUE TITLE
Pedal Requests + Updates!

### ISSUE THREAD

**Issue by rockrockrokk** [PedalPlayground/pedalplayground#1823]
Carl Martin Hydra Boost (2.55in x 4.32in)
![Carl Martin Hydra Boost (2 55in x 4 32in)](https://github.com/PedalPlayground/pedalplayground/assets/160074168/807a62b3-ee26-46fa-a311-dce0e92b843f)
XTS Iridium Fuzz (2.85in x 4.5in)
![XTS Iridium Fuzz (2 85in x 4 5in)](https://github.com/PedalPlayground/pedalplayground/assets/160074168/2140b4cd-1db2-41b9-a597-8714c29acf6a)
![XTS Iridium Fuzz 2 (2 85in x 4 5in)](https://github.com/PedalPlayground/pedalplayground/assets/160074168/552bba40-04d0-4698-b0a6-fde9f7437358)
Voodoo Lab X4 (3.38in x 2.75in) [This is the only good top-down image that I could find... :/]
![Voodoo Lab X4 (3 38in x 2 75in)](https://github.com/PedalPlayground/pedalplayground/assets/160074168/15a05e7c-c088-420c-9e36-b9f8e940c59b)
Voodoo Lab X8 (5.5in x 2.75in)
![Voodoo Lab X8 (5 5in x 2 75in)](https://github.com/PedalPlayground/pedalplayground/assets/160074168/49478eda-3515-4c09-a9b4-0a2b7a14253c)

Updates:
Voodoo Lab Pedal Power 2+ (6in x 3.4in)
![Voodoo Lab Pedal Power 2+ (6in x 3 4in)](https://github.com/PedalPlayground/pedalplayground/assets/160074168/49c88531-1ecd-48e7-827f-30da72f805b0)
Voodoo Lab Pedal Power ISO 5 (4.9in x 3.4in)
![Voodoo Lab Pedal Power ISO 5 (4 9in x 3 4in)](https://github.com/PedalPlayground/pedalplayground/assets/160074168/bd49e868-21cb-4819-aa21-b25b99f2035e)

**Comment by ArislanShiva** [comment]
Next time please create a separate issue for each pedal. Thanks.
