### ISSUE TITLE
Pedal request : Jim Dunlop MXR CSP033 IL Torino Overdrive / MXR CSP 033

### ISSUE THREAD

**Issue by Artheius** [PedalPlayground/pedalplayground#1853]
Manufacturer: MXR
Model: MXR IL Torino Overdrive CSP-033
Dimensions (WxHxD / cm) : 6,0 x 3,2 x 11,1

![9807702_12519475-8273-48ab-8fec-ec81e248680a_1400_1400](https://github.com/PedalPlayground/pedalplayground/assets/102348380/a0af9b0f-411b-4996-8960-5607dc753dd2)

**Comment by ArislanShiva** [comment]
Also already in the database.
