### ISSUE TITLE
Pedal Request: Electro Harmonix NANO Q-TRON ENVELOPE CONTROLLED FILTER

### ISSUE THREAD

**Issue by Artheius** [PedalPlayground/pedalplayground#1854]
Height:	2.1"
Width:	2.75"
Depth:	4.5"

![ed52e1-~edited_nanoqtron jpeg auto](https://github.com/PedalPlayground/pedalplayground/assets/102348380/e26586bd-10e5-4110-82b0-bd4f88ad19e0)

**Comment by ArislanShiva** [comment]
Already in the database.
