### ISSUE TITLE
Pedal Request: PlexiTone-S Guitar Distortion Effect Pedal

### ISSUE THREAD

**Issue by Artheius** [PedalPlayground/pedalplayground#1855]
Product Dimensions | 5 x 3.5 x 3 inches

![61dj+JvHW2L _AC_SX679_](https://github.com/PedalPlayground/pedalplayground/assets/102348380/2f7bbe71-6b9d-429d-b6b1-bdf812cec059)

**Comment by ArislanShiva** [comment]
Also in the database...
