### ISSUE TITLE
Pedal Requests: Sound Sculpture Volcano and The Pill Pedal Mini

### ISSUE THREAD

**Issue by ZYMECORE** [PedalPlayground/pedalplayground#1857]
![Sound Sculpture Volcano](https://github.com/PedalPlayground/pedalplayground/assets/113817413/04c0059e-c7fd-427c-9944-16b25e7a9e58)
Unique space saving volume module that uses an external expression pedal to control gain. Good for stacking under other pedals.
2.5" x 4.59" with protrusions

![Pill Pedal Mini](https://github.com/PedalPlayground/pedalplayground/assets/113817413/902260ae-3028-4978-b812-4cb63c076b4e)
Measurements include protrusions.
4.375" x 2.703"

**Comment by XlosVSM** [comment]
@ArislanShiva you didn't add the pill

**Comment by ZYMECORE** [comment]
> @ArislanShiva you didn't add the pill

The full size is the database already. This is the original mono version!
