### ISSUE TITLE
Pedal Request: Origin Effects Cali76 FET (Black and Regular versions)

### ISSUE THREAD

**Issue by tdillonsd** [PedalPlayground/pedalplayground#1863]
Please add the Origin Effects Cali76 FET compressor pedal, black version and regular version

Dimensions are: 124 x 64 x 58 mm (4.8 x 2.5 x 2.3 in.)

![Origin-Effects-Cali76-FET-Compressor-Feature-Image-2-Black](https://github.com/PedalPlayground/pedalplayground/assets/52335215/35f1903a-721b-4b50-a4f4-19f6022bfad5)

![Origin-Effects-Cali76-FET-Compressor-Feature-Image-1](https://github.com/PedalPlayground/pedalplayground/assets/52335215/383040da-dc93-4140-8742-b0c30a9839a9)

Thanks!

**Comment by ArislanShiva** [comment]
These were recently added in #1817.

Please close this issue, thanks.

**Comment by tdillonsd** [comment]
Closed. Duplicate issue to 1817.
