### ISSUE TITLE
Pedal Update Request

### ISSUE THREAD

**Issue by tdillonsd** [PedalPlayground/pedalplayground#1864]
Please update the existing graphic for the Becos Ziffer Overdrive Pedal item already in the Pedal Playground database.

Dimensions are:  9,3 × 5 × 5,1 cm or 3.66 x 1.96 x 2.01 in
The current graphic image has been squeeze to be too narrow.

![TS8-01](https://github.com/PedalPlayground/pedalplayground/assets/52335215/4338e4e9-9260-4eab-8d71-52857d0164f8)

**Comment by ArislanShiva** [comment]
This was recently fixed in #1817.

Please close this issue, thanks.

**Comment by tdillonsd** [comment]
Closed. Duplicate issue to 1817.
