### ISSUE TITLE
Pedal Request: Dunlop QZ1 Cry Baby Q-Zone Fixed Wah

### ISSUE THREAD

**Issue by Thewordisf** [PedalPlayground/pedalplayground#1872]
Dunlop QZ1 Cry Baby Q-Zone Fixed Wah

4.33 in x 2.55 in

![dunlop-qz1-cry-baby-q-zone-fixed-wah](https://github.com/PedalPlayground/pedalplayground/assets/108265156/bbd3a30a-7e2b-448d-b640-0f2ac516fe76)

**Comment by ArislanShiva** [comment]
Already on the site under the brand "Cry Baby" instead of "Dunlop".

(No idea why it's like that... probably needs to be changed)

Please close this issue, thanks.
