### ISSUE TITLE
[ Site Issue ] Pedalboard.app using our image data without permission

### ISSUE THREAD

**Issue by ArislanShiva** [PedalPlayground/pedalplayground#1875]
@tehtrav 

Not sure if you're aware but there's a new pedalboard app that was released a week or so ago on Reddit called [Pedalboard.app](https://www.reddit.com/r/guitarpedals/comments/1ctcbls/i_made_the_pedalboard_builder_i_always_wanted/). 

They have essentially lifted our entire image library, which includes many hand illustrated boards, composited/edited pedals, originally photographed pedals, etc.  I'm sure if we looked under the hood there would probably be quite a bit of your code and ideas in there too.

If it were just another community passion project like this one then I might not mind but they've monetized their site with affiliate links.  Having somebody profit off hours of our work doesn't sit well with me.

What would you propose that we do about this issue, if anything?

**Comment by tehtrav** [comment]
@ArislanShiva thanks for bringing this to my attention! I will reach out to the author to see if we can get at the very least the from-scratch assets removed.
