### ISSUE TITLE
Pedal Request: Diamond Vibrato (reissue)

### ISSUE THREAD

**Issue by Thewordisf** [PedalPlayground/pedalplayground#1876]
Diamond Vibrato 2024 reissue

4.8” x 2.64”

![Vibrato_Front copia](https://github.com/PedalPlayground/pedalplayground/assets/108265156/bdd930c7-eab9-4561-aa1d-1ed061fe48d2)

**Comment by ArislanShiva** [comment]
Was already added in #1866
