### ISSUE TITLE
Pedal request: Diamond Vibrato (the new one)

### ISSUE THREAD

**Issue by Ripley63** [PedalPlayground/pedalplayground#1878]
There's already the old Diamond Vibrato in the DB, but can you add their newest iteration of the same pedal?

Dimensions (measured by me)
W 6,7 cm
H 12,4 cm (with in/out thickness)

Dimensions (from Diamond webpage)
W 2,64 in
H 4,80 in

The image is from Diamond webpage, I've made it png and cut out some background.

![Vibrato_Front](https://github.com/PedalPlayground/pedalplayground/assets/85568509/0b3222ba-02f3-47b4-b85c-e2f7d1913a0d)

**Comment by ArislanShiva** [comment]
It was already added in #1866 which hasn't been pushed to the active site yet.

**Comment by Ripley63** [comment]
Cool thanks.
