### ISSUE TITLE
Pedal Request: VDL (1) , Solo Dallas (2)

### ISSUE THREAD

**Issue by JaehwiSong129** [PedalPlayground/pedalplayground#1900]
Thank you!

VDL - Distorsore (W: 120mm, H: 94mm)
![VDl_Distorsore](https://github.com/PedalPlayground/pedalplayground/assets/172505695/4eb482cd-d9c8-420f-812a-3d9bc942bbf8)

Solo Dallas - Storm (W: 64mm, H: 120mm)
![SD_storm](https://github.com/PedalPlayground/pedalplayground/assets/172505695/3f2ac413-851c-4d6b-83fe-51f1ef389bc1)

Solo Dallas - BassX (W: 64mm, H: 120mm)
![SD_BassX](https://github.com/PedalPlayground/pedalplayground/assets/172505695/4df283a0-cea3-4c15-9689-4c8fdc7adfc6)

**Comment by jpitchardu** [comment]
Bass-X is in: https://github.com/PedalPlayground/pedalplayground/pull/1881
