### ISSUE TITLE
Pedal Request: More Henretta Engineering Pedals

### ISSUE THREAD

**Issue by monkeydawg92** [PedalPlayground/pedalplayground#1906]

**Comment by ArislanShiva** [comment]
Requests must include the following:

1. The pedal brand and **name** in the title of your request,
2. **A high resolution image of the pedal** (top-down view, preferably white background, straight on perspective),
3. **The dimensions of the pedal in inches** (make sure the dimensions are accurate and include jacks and other protrusions).

**Please post a new issue for each pedal you are requesting!**
