### ISSUE TITLE
Pedal request: Catalinbread Dirty Little Secret (Purple)

### ISSUE THREAD

**Issue by bduce81** [PedalPlayground/pedalplayground#1918]
Thank you!

dimensions = 2.7" x 4.5"

![dirty little secret mk3 purple](https://github.com/user-attachments/assets/0d2bc772-3782-470f-9e90-4a3cd0618486)

**Comment by ArislanShiva** [comment]
- Please do not request alternative colorways. To help keep the project size manageable we will no longer be accepting those requests
