### ISSUE TITLE
Pedal Request: Electro-Harmonix POG3

### ISSUE THREAD

**Issue by JaehwiSong129** [PedalPlayground/pedalplayground#1922]
Electro-Harmonix POG3
Dimensions: 7.125 x 5.75 x 2.25 (in)

![pog3](https://github.com/user-attachments/assets/0b0719d1-e81c-42ff-975b-cb22100b6599)

**Comment by ArislanShiva** [comment]
**Before you submit, please consider the following:**

- New releases from all major builders are added to the database automatically -- there is no need to make a request for those,
