### ISSUE TITLE
Add Pedal - Microcosm (BLACK version)

### ISSUE THREAD

**Issue by timswansiger** [PedalPlayground/pedalplayground#1929]
<img width="1190" alt="Microcosm (Black)" src="https://github.com/user-attachments/assets/ac1b5ad3-adc4-4cf0-8f86-a8a9121b7f00">

Dimensions: 7.1 x 4.7 x 2.0 inches

**Comment by ArislanShiva** [comment]
**Before you submit, please consider the following:**

- Please do not request alternative colorways. To help keep the project size manageable we will no longer be accepting those requests

**Comment by timswansiger** [comment]
Aesthetics are a big part of pedalboard development.  You should reconsider this approach.On Aug 15, 2024, at 12:37 PM, ArislanShiva ***@***.***> wrote:﻿
Before you submit, please consider the following:

Please do not request alternative colorways. To help keep the project size manageable we will no longer be accepting those requests

**Comment by ArislanShiva** [comment]
> Aesthetics are a big part of pedalboard development.  You should reconsider this approach.

Regardless, please adhere to site guidelines in the future when making requests.  Thank you.

**Comment by timswansiger** [comment]
Sorry about that.  I didn’t notice anything stating it was not allowed.On Aug 15, 2024, at 12:45 PM, ArislanShiva ***@***.***> wrote:﻿

Aesthetics are a big part of pedalboard development.  You should reconsider this approach.

Regardless, please adhere to site guidelines in the future when making requests.  Thank you.
