### ISSUE TITLE
Pedal Request: Cusack Tap-A-Whirl V4 (Black)

### ISSUE THREAD

**Issue by monkeydawg92** [PedalPlayground/pedalplayground#1932]
![Tap-a-whirl Black](https://github.com/user-attachments/assets/91677894-e5da-417d-b8b9-be274978430d)

Dimensions: 4.75” x 3.85” x 2.25” (L x D x H)

**Comment by ArislanShiva** [comment]
Before you submit, please consider the following:

- Please do not request alternative colorways. To help keep the project size manageable we will no longer be accepting those requests
