### ISSUE TITLE
Pedal Request: Twilight Pulse Audioworks - Konstante Overdrive (White, Grey)

### ISSUE THREAD

**Issue by JaehwiSong129** [PedalPlayground/pedalplayground#1972]
W: 66.5 mm
H: 122 mm

![KakaoTalk_20241018_113132305](https://github.com/user-attachments/assets/eb5d2d9c-fc41-469e-8c15-88e9e40909a8)
![KakaoTalk_20241018_113225806](https://github.com/user-attachments/assets/8d8f2392-afdb-4c6f-9c4c-1818ce330035)

**Comment by ArislanShiva** [comment]
These are already in the database.  Please close this issue, thanks.

**Comment by JaehwiSong129** [comment]
Oh I misspelled the search.
Then, could you add a color logo(black) version?

**Comment by ArislanShiva** [comment]
We already have three colorways for that pedal in the database and it's not exactly a popular product.  Can't really see adding a 4th colorway for it.

I could replace the "negative black" version with the standard black edition tho.

**Comment by JaehwiSong129** [comment]
Then please replace the black version image. Thank you!
