### ISSUE TITLE
Some dimensions mismatch

### ISSUE THREAD

**Issue by Ripley63** [PedalPlayground/pedalplayground#1973]
Hi,
just a heads-up to correct the dimensions of the...Boss Dimension C (no pun intended).
See my (real) Nano+ with a Keeley Halo and a Boss DC-2w side by side.
On PP the 2 Boss pedals look much smaller then in reality.
The Friedman Smallbox looks correct (jus a tad smaller than the Halo).
Looking at the real BD-2, probably some other Boss pedals also need a correction of some sort.

The MXR Timmy suffers the same fate as the Boss, but in reality it is as long as the Xotic SP Compressor (9cm), but on PP it looks smaller.
It gets even stranger: clicking on PP's Timmy, its dimensions are listed as 44mm x **94mm**, and PP's SP Compressor is 48mm x **94mm**, so they should both look as long as each other, but they don't.

![2024-10-20 22 05 52](https://github.com/user-attachments/assets/38bc9688-3dac-4bc1-9bf6-d99014b07487)

![Clipboard01](https://github.com/user-attachments/assets/db37e988-4a4e-43b4-9655-968b55e818ab)

**Comment by ArislanShiva** [comment]
Looks like you must have changed the scale at some point and the site bugged out.  Try resetting your board or cleaning out your browser cookies.  I assure you those size issues aren't present on the current build of the site.

**Comment by Ripley63** [comment]
You're right!
It was enough to change the scale factor, and pedals were correctly resized.
