### ISSUE TITLE
Pedal Request: JHS The Violet

### ISSUE THREAD

**Issue by jplee3** [PedalPlayground/pedalplayground#1998]
![violet_black](https://github.com/user-attachments/assets/9b7368f3-15e3-4d4a-9861-887dd07d1fba)

![violet_purple](https://github.com/user-attachments/assets/5613fbdf-f53d-471e-a5a8-50efa96a0bae)

4.7” X 3.5” X 1.5” 
https://jhspedals.info/collections/all-products/products/the-violet

**Comment by ArislanShiva** [comment]
Already added in #1980, please close this issue.

**Comment by jplee3** [comment]
> Already added in #1980, please close this issue.

Was this checked-in and is it supposed to be on the site now? I searched for it and am not seeing it on the list of available pedals

**Comment by ArislanShiva** [comment]
> Even if your request has been completed and linked to a pull request it may still take several weeks for updates to get pulled into the main project. The individual contributors have no control over that so please remain patient.

Gotta wait for the site owner to pull the updates in.
