### ISSUE TITLE
Pedal Request: Walrus Audio Voyager Mkii (black as well as standard colorway)

### ISSUE THREAD

**Issue by monkeydawg92** [PedalPlayground/pedalplayground#2007]
![IMG_9650](https://github.com/user-attachments/assets/efaf13f2-cf2e-4349-9aa3-719c9f0f0134)

![IMG_9651](https://github.com/user-attachments/assets/eff93006-f506-4e12-bbce-eeac53b857ab)

2.62 x 4.77 x 2.25

**Comment by ArislanShiva** [comment]
These were added in #1980.  Please close this issue, thanks.
